name = "groupchat"
main = "src/app.js"
workers_dev = true
compatibility_date = "2025-07-07"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "GROUPCHAT_DURABLE_OBJECT"
class_name = "GroupchatDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GroupchatDurableObject"]

[assets]
directory = "./dist/"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"